<!DOCTYPE html>
<html lang="en">

<head>
          <base href="/factura.local" />
          <meta charset="UTF-8" />
          <title><?= $title ?></title>
          <meta name="description" content="<?= $description ?>" />
          <link rel="stylesheet" href="../assets/css/bootstrap.min.css" type="text/css"/>
          <link rel="stylesheet" href="../assets/css/now-ui-dashboard.css?v=1.5.0" type="text/css"/>
          <link rel="stylesheet" href="../assets/css/perso.css" type="text/css"/>
          <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
          <link rel="icon" type="image/png" href="../assets/img/favicon.png">
          <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
          <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
         
          <!--     Fonts and icons     -->
          <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
          <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


          <!-- Modal -->
          <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
</head>

<body class="">

          <?php 
                       $this->controller->renderView(); 
          ?>

</body>

</html>