<!DOCTYPE html>
<html lang="en">
          <head>
                    <base href="/factura.local" />
                    <meta charset="UTF-8" />
                    <title><?= $title ?></title>
                    <meta name="description" content="<?= $description ?>" />
                    <link rel="stylesheet" href="../assets/css/bootstrap.min.css" type="text/css"/>
                    <link rel="stylesheet" href="../assets/css/now-ui-dashboard.css?v=1.5.0" type="text/css"/>
                    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
                    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
                    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
                    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
                    <!--     Fonts and icons     -->
                    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
                    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
                    
                    <link rel="stylesheet" href="../assets/css/perso.css" type="text/css"/>
                    <link href="../assets/demo/demo.css" rel="stylesheet" />
                    <!-- Modal -->
                    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
                    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" /> -->
                    <script src="../assets/js/core/jquery.min.js"></script>
                    <script src="../assets/js/jquery.modal.min.js"></script>
                    <link rel="stylesheet" href="../assets/css/jquery.modal.min.css" />

          </head>

          <body>
                    <div class="wrapper">
                              <div class="sidebar" data-color="blue"> -->
                                        <!--
                                        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
                                        -->
                                        <div class="logo">
                                                  <a href="http://www.creative-tim.com" class="simple-text logo-mini">F</a>
                                                  <a href="http://www.creative-tim.com" class="simple-text logo-normal">  Factura </a>
                                        </div>
                                        <div class="sidebar-wrapper" id="sidebar-wrapper">
                                                  <ul class="nav">
                                                            <li class="active ">
                                                            <a href="/modeles">
                                                            <i class="now-ui-icons design_app"></i>
                                                            <p>Modèles</p>
                                                            </a>
                                                            </li>
                                                            <li>
                                                            <a href="./icons.html">
                                                            <i class="now-ui-icons education_atom"></i>
                                                            <p>Personnaliser</p>
                                                            </a>
                                                            </li>
                                                            <li>
                                                            <a href="./map.html">
                                                            <i class="now-ui-icons location_map-big"></i>
                                                            <p>Mes factures</p>
                                                            </a>
                                                            </li>
                                                            <!-- <li>
                                                            <a href="./notifications.html">
                                                            <i class="now-ui-icons ui-1_bell-53"></i>
                                                            <p>Notifications</p>
                                                            </a>
                                                            </li>-->
                                                            <li> 
                                                            <a href="/users">
                                                            <i class="now-ui-icons users_single-02"></i>
                                                            <p>Utlisateurs</p>
                                                            </a>
                                                            </li>
                                                            <!-- <li>
                                                            <a href="./tables.html">
                                                            <i class="now-ui-icons design_bullet-list-67"></i>
                                                            <p>Table List</p>
                                                            </a>
                                                            </li>
                                                            <li>
                                                            <a href="./typography.html">
                                                            <i class="now-ui-icons text_caps-small"></i>
                                                            <p>Typography</p>
                                                            </a>
                                                            </li> -->
                                                            <li class="active-pro">
                                                            <a href="./upgrade.html">
                                                            <i class="now-ui-icons arrows-1_cloud-download-93"></i>
                                                            <p>Obtenir un abonnement</p>
                                                            </a>
                                                            </li>
                                                  </ul>
                                        </div>
                              </div>
                              
                              <div class="main-panel" id="main-panel">
                                           
                                        <!-- Navbar -->
                                        <nav class="navbar navbar-expand-lg navbar-transparent  bg-primary  navbar-absolute">
                                                  <div class="container-fluid">
                                                  <div class="navbar-wrapper">
                                                            <div class="navbar-toggle">
                                                            <button type="button" class="navbar-toggler">
                                                            <span class="navbar-toggler-bar bar1"></span>
                                                            <span class="navbar-toggler-bar bar2"></span>
                                                            <span class="navbar-toggler-bar bar3"></span>
                                                            </button>
                                                            </div>
                                                            <a class="navbar-brand" href="#pablo">Dashboard</a>
                                                  </div>
                                                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                                                            <span class="navbar-toggler-bar navbar-kebab"></span>
                                                            <span class="navbar-toggler-bar navbar-kebab"></span>
                                                            <span class="navbar-toggler-bar navbar-kebab"></span>
                                                  </button>
                                                  <div class="collapse navbar-collapse justify-content-end" id="navigation">
                                                            <form>
                                                            <div class="input-group no-border">
                                                            <input type="text" value="" class="form-control" placeholder="Rechercher...">
                                                            <div class="input-group-append">
                                                            <div class="input-group-text">
                                                            <i class="now-ui-icons ui-1_zoom-bold"></i>
                                                            </div>
                                                            </div>
                                                            </div>
                                                            </form>
                                                            <ul class="navbar-nav">
                                                            <li class="nav-item">
                                                            <a class="nav-link" href="#pablo">
                                                            <i class="now-ui-icons media-2_sound-wave"></i>
                                                            <p>
                                                            <span class="d-lg-none d-md-block">Stats</span>
                                                            </p>
                                                            </a>
                                                            </li>
                                                            <li class="nav-item dropdown">
                                                            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                            <i class="now-ui-icons location_world"></i>
                                                            <p>
                                                            <span class="d-lg-none d-md-block">Some Actions</span>
                                                            </p>
                                                            </a>
                                                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                                            <a class="dropdown-item" href="#">Action</a>
                                                            <a class="dropdown-item" href="#">Another action</a>
                                                            <a class="dropdown-item" href="#">Something else here</a>
                                                            </div>
                                                            </li>
                                                            <li class="nav-item">
                                                             <!-- <a class="nav-link" href="/users/logout"> -->
                                                            <a class="nav-link logouting">
                                                                      <i class="now-ui-icons arrows-1_share-66"></i>
                                                                      <p>
                                                                                <span class="d-lg-none d-md-block">Compte</span>
                                                                      </p>
                                                            </a>
                                                            </li>
                                                            </ul>
                                                  </div>
                                                  </div>
                                        </nav>
                                        <!-- <div id="msg"></div> -->
                                        <?php
                                                  $this->controller->renderView(); 
                                                  //var_dump( $this->controller);
                                         ?>

                                        <footer class="footer">
                                                  <div class=" container-fluid ">
                                                            <div class="copyright" id="copyright">&copy; <script>
                                                            document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))
                                                            </script>, Conception par <a href="https://www.dextrem.agency" target="_blank">Dextrem</a>.
                                                            </div>
                                                  </div>
                                        </footer>
                              </div>
                    </div>

                    

          </body>

          <!--   Core JS Files   -->
          <script src="../assets/js/core/jquery.min.js"></script>
          <script src="../assets/js/core/popper.min.js"></script>
          <script src="../assets/js/core/bootstrap.min.js"></script>
          <script src="../assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
          <!--  Google Maps Plugin    -->
          <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
          <!-- Chart JS -->
          <script src="../assets/js/plugins/chartjs.min.js"></script>
          <!--  Notifications Plugin    -->
          <script src="../assets/js/plugins/bootstrap-notify.js"></script>
          <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
          <script src="../assets/js/now-ui-dashboard.min.js?v=1.5.0" type="text/javascript"></script><!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
          <script src="../assets/js/perso.js"></script>
          <script>
                    $(document).ready(function() {
                    // Javascript method's body can be found in assets/js/demos.js
                    // demo.initDashboardPageCharts();

                    });
          </script>
</html>