<div class="wrapper ">

<div class="mainhome-panel" id="main-panel">

  
  <div class="panel-header panel-header-sm">
  </div>
  
  <div class="content">
       <div class="col-md-3">
      </div>
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">
            <h5 class="title">Connexion</h5>
          </div>
          <div class="card-body">
            <form  action="<?="login/login";?>" method="post">
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label>Email</label>
                    <input type="email" name="email" class="form-control" placeholder="hello@me.com">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label>Mot de passe(password)</label>
                    <input type="password" name="password" class="form-control" placeholder="********">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <input type="text" name="csrf_token" value="<?=Token::generate(); ?>" />
                </div>
              </div>

              <div class="row">
                <div class="col-md-12">
                  <button type="submit" class="btn btn-primary btn-round">
                    Se connecter
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="col-md-3">

      </div>
  </div>

</div>
</div>